name: build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ZIP entpacken
        run: unzip -o -q "*.zip"
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.14.3
      - run: gradle build --stacktrace
        working-directory: krieger-fabric
      - uses: actions/upload-artifact@v4
        with:
          name: KriegerMod-jar
          path: krieger-fabric/build/libs/*.jar
